id: sync_git
namespace: prod.sync

tasks:
  - id: sync
    type: io.kestra.plugin.git.TenantSync
    uri: https://github.com/mocomakers/nf_streamlit
    branch: main
    directory: kestra/flows

triggers:
  - id: gh_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
