name: deploy-to-server
on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      prod_private_key: ${{ secrets.prod_private_key }}
      prod_user: ${{ secrets.prod_user }}
      prod_path: ${{ secrets.prod_path }}
      prod_url: ${{ secrets.url }}
    steps:
      - if: ${{ env.prod_private_key == '' }}
        run: echo 'This step will only run if the secret has a value set.'
      - if: ${{ env.prod_private != '' }}
        run: |
           echo 'This step has the prod_pass' \
           eval $(ssh-agent -s) \
           ssh-add <(echo "$prod_private_key")
            
